### ISSUE TITLE
Random Suggestions

### ISSUE THREAD

**Issue by switz** [splewis/csgo-multi-1v1#102]
1v1 retakes: T is spawned offsite somewhere with the bomb already planted, while CT is spawned nearby. Must retake the site against one person.

continuous 1v1: the ladder system is fun, but essentially meaningless. I'd much rather just get thrown into an arena immediately after dying with someone who has similar ELO and has also died, for rapid gameplay and minimal downtime.

Keep up the great work.

**Comment by splewis** [comment]
For the 2nd idea:
- removing the round-based system would require a large rewrite
- pairing players by elo tends to not work well since it has such a small player population

The two combined would be an even more significant rewrite, and made even more challenging than in isolation since you'd have to take delicate care to make sure people don't just end up matched against the same 1-2 players over and over.

If I were to take those ideas (which aren't new at all) - I'd probably do a full overhaul and probably use [glicko2](http://www.glicko.net/glicko/glicko2.pdf) as the base rating system. I don't see that happening anytime soon, though.

**Comment by switz** [comment]
I totally understand. Thanks again.
