### ISSUE TITLE
Error Log [Can you please tell me what is wrong]

### ISSUE THREAD

**Issue by JRS-HowlServers** [splewis/csgo-multi-1v1#159]
Here is the log in a pastebin: http://pastebin.com/4V3tW6Fg
HLStats does not seem to want to work after installing Multi1v1, is there a way to fix this. Or how do I set up the built-in stats interface. [Sorry, New to all of this stuff]

**Comment by splewis** [comment]
There's several issues:
> L 11/22/2016 - 19:48:31: [multi1v1.smx] Failed to open file for reading: cfg/sourcemod/multi1v1/game_cvars.cfg

Your server is missing write permissions in that directory, so that's a fix. I can't help you fix that, though.

As for the stats, there's help at https://github.com/splewis/csgo-multi-1v1/wiki/Standard-stats-setup.

I don't know why your logs are spammed with the 
> L 11/22/2016 - 19:48:54: [SM]   [1] Line 131, ./scripting/multi1v1/natives.sp::Native_GetArenaNumber

exception. Can you provide a version number you're using? ``sm plugins`` will display them.

**Comment by JRS-HowlServers** [comment]
Version 1.1.4. And how do I keep bots from joining after idle time?

**Comment by JRS-HowlServers** [comment]
Figured out the bots error
