### ISSUE TITLE
Helmet/kevlar in normal rounds

### ISSUE THREAD

**Issue by die-man** [splewis/csgo-multi-1v1#189]
Hi,
How i can override helmet/kevlar in normal rounds?
I change some configs (and install some plugins), but multi-1v1 always put helmet+kevlar in all players.

i dont want this :(

Thanks.

**Comment by splewis** [comment]
The only way this is supported is by writing another plugin using the [api](https://github.com/splewis/csgo-multi-1v1/blob/master/scripting/include/multi1v1.inc) that calls ``Multi1v1_ClearRoundTypes``  in ``Multi1v1_OnRoundTypesAdded`` and readding the roundtypes how ever you want them to work.

There's no special override because I don't see the value in changing the kevlar/helmet behavior on the default round types.
