### ISSUE TITLE
workshop map isse

### ISSUE THREAD

**Issue by imsandeshjagtap** [splewis/csgo-multi-1v1#200]
i am using workshop multi player arena maps 
but i cat find max rounds option
and how set all workshop maps only in next round
its get change to d2 :(

**Comment by splewis** [comment]
I think you're asking 2 questions:

1. Setting maxrounds. By default the plugin configs set mp_timelimit instead of mp_maxrounds. You could try to set whatever cvars you want in ``cfg/sourcemod/multi1v1/game_cvars.cfg``. I would not suggest trying to set mp_maxrounds.

2. How to set the map rotation. That's completely irrelevant to this plugin. [This page](https://wiki.alliedmods.net/Map_Management_Plugins_(SourceMod)) will probably help. It has nothing to do with the gamemode.
