### ISSUE TITLE
Error on no 1x1 maps

### ISSUE THREAD

**Issue by baferpro** [splewis/csgo-multi-1v1#202]
I keep a server that has a lot of mods.
On some cards, I turn off the plugin ( sm_multi1v1_enabled 0 ). But plugin print in error 
```[multi1v1.smx] No arenas could be found for this map!```
How to fix?

**Comment by splewis** [comment]
There's no way to fix it right now.

I'd accept a pull request that defers the spawn-searching that causes this error until sm_multi1v1_enabled is first set to 1 each map, instead of always running it in [OnMapStart](https://github.com/splewis/csgo-multi-1v1/blob/master/scripting/multi1v1.sp#L426), though.
