### ISSUE TITLE
People sometimes get frozen when joining the server

### ISSUE THREAD

**Issue by BrutalCSkakan** [splewis/csgo-multi-1v1#84]
I don't have so much info right now, giving you some errors anyways
We got a post in the Alliedmodders thread too, https://forums.alliedmods.net/showpost.php?p=2251143&postcount=544

L 01/19/2015 - 19:10:29: [SM] [0] Line 350, csgo/addons/sourcemod/scripting/multi1v1.sp::Event_OnRoundPostStart()
L 01/19/2015 - 19:10:29: [SM] Plugin encountered error 15: Array index is out of bounds

**Comment by BrutalCSkakan** [comment]
L 01/13/2015 - 22:01:05: [SM] Displaying call stack trace for plugin "multi1v1.smx":
L 01/13/2015 - 22:01:05: [SM]   [0]  Line 22, csgo/addons/sourcemod/scripting/multi1v1/queue.sp::Queue_Find()
L 01/13/2015 - 22:01:05: [SM]   [1]  Line 14, csgo/addons/sourcemod/scripting/multi1v1/queue.sp::Queue_Enqueue()
L 01/13/2015 - 22:01:05: [SM]   [2]  Line 601, csgo/addons/sourcemod/scripting/multi1v1.sp::JoinGame()
L 01/13/2015 - 22:01:05: [SM]   [3]  Line 594, csgo/addons/sourcemod/scripting/multi1v1.sp::Command_TeamJoin()
L 01/13/2015 - 22:01:05: [multi1v1.smx] player MoeMoe had arena -1 on his spawn
L 01/13/2015 - 22:01:14: [SM] Native "FindValueInArray" reported: Invalid Handle 214020f (error: 3)
L 01/13/2015 - 22:01:14: [SM] Displaying call stack trace for plugin "multi1v1.smx":

**Comment by BrutalCSkakan** [comment]
And now one of our servers crasched without a single error..

**Comment by splewis** [comment]
> As Ejziponken says in the thread, we're using 4 servers connected to the same database, right now it has 41k players.. Could it be a problem?

I personally have 4 server with 120K players in my database, so no. However, 0.5.2 still used same-thread SQL queries and there were some weird edge cases that could cause errors to (rarely) occur. The plugin now does it properly and uses threaded queries to get everything done. 

One thing you could try is to disable the stats and see if stability improves.

You could also upgrade to a development version of this plugin since it's much more stable now (hopefully when sourcemod1.7 comes out I can release it again). You would need to update your servers to a 1.7 snapshot, however.

**Comment by supimfuzzy** [comment]
Did not have that problem with around 140k players in my DB before I shut down.

**Comment by BrutalCSkakan** [comment]
L 01/24/2015 - 22:00:42: [multi1v1.smx] Failed to fetch statistics for for ✪KirstenFraHobro✪<2><STEAM_1:1:76557646><>
L 01/24/2015 - 22:00:46: [multi1v1.smx] Failed to fetch statistics for for ✪KirstenFraHobro✪<2><STEAM_1:1:76557646><>
L 01/24/2015 - 22:00:59: [multi1v1.smx] Failed to fetch statistics for for ✪KirstenFraHobro✪<2><STEAM_1:1:76557646><>


L 01/24/2015 - 21:36:36: [multi1v1.smx] AThornnn<1853><STEAM_1:1:106042784><> had arena -1 on player spawn event
L 01/24/2015 - 21:37:31: [multi1v1.smx] Mr.FELIX<1854><STEAM_1:0:44141571><> had arena -1 on player spawn event
L 01/24/2015 - 21:37:52: [multi1v1.smx] blåbärspaj<1855><STEAM_1:0:60537752><> had arena -1 on player spawn event

**Comment by erikxcore** [comment]
Just ran into this issue the other night, haven't had any problems on 0.5.2 or 1.0.0 until last night. Run a few other servers on this VPS that experienced no issues so it's isolated to the multi1v1 server.
MySQL running on localhost, no errors in the logs there, other serves using hlstatsxce without a problem on a different table/user.
Servers have daily resets, since your update to 1.0.0/requiring SM1.7.0 haven't had an issue until last night. MM version 1.10.4
VPS is on Ubuntu 12.10, 8gb RAM, decent quad core CPU. At most memory usage doesn't go above 75%.

L 02/19/2015 - 00:46:14: SourceMod error session started
L 02/19/2015 - 00:46:14: Info (map "workshop/279697343/am_grass2") (file "errors_20150219.log")
L 02/19/2015 - 00:46:14: [/disabled/multi1v1.smx] XXX<177><STEAM_X:X:XXXXXXXXX><> had arena -1 on player spawn event
L 02/19/2015 - 00:46:14: [SM] Plugin encountered error 15: Array index is out of bounds
L 02/19/2015 - 00:46:14: [SM] Displaying call stack trace for plugin "/disabled/multi1v1.smx":
L 02/19/2015 - 00:46:14: [SM]   [0]  Line 141, ./scripting/multi1v1/natives.sp::Native_GetArenaPlayer1()
L 02/19/2015 - 00:46:14: [SM] Plugin encountered error 4: Invalid parameter or parameter type
L 02/19/2015 - 00:46:14: [SM] Native "Multi1v1_GetArenaPlayer1" reported: Arena -1 is not valid
L 02/19/2015 - 00:46:14: [SM] Displaying call stack trace for plugin "/disabled/multi1v1_flashbangs.smx":
L 02/19/2015 - 00:46:14: [SM]   [0]  Line 55, ./scripting/multi1v1_flashbangs.sp::Multi1v1_AfterPlayerSpawn()

Seems like this occurred as soon as 1 user joined in and woke the server up from hibernation (thinking this could be the issue), he attempted to rtv using rockthevote_extended/mapchooser_extended but it seems like those commands never fired, either (nothing in logs); the only thing abnormal thing about this user (he's a regular) was a lot of pure server file checks e.g. 
[STEAM_X:X:XXXXXXX] Pure server: file: GAME\materials/models/gmod_tower/sombrero.vmt ( 1 83 53 ) could not open file to hash ( benign for now ) : c96d826e16f343d389b2f95e44f94748 :
3 minutes prior to this someone joined the server and left without any issues.

Anyhow, trying to see if it will occur again today but I disabled all plugins except the base multi1v1.smx. I seem to recall hitting these errors when we had sv_allowvotes to 1 and people were voting for incompatible maps but I don't think that's the case here.

**Comment by BrutalCSkakan** [comment]
The reason for RTV to not fire is because he was alone on the server, I think that RTV needs atleast ~5 players connected as standard.
